#!/bin/bash
# Display notify-send notifications via remote SSH


if [[ -z $DBUS_SESSION_BUS_ADDRESS ]]; then
    pidlist=$(pgrep -u "$USER" 2>/dev/null)
    if [[ -n $pidlist ]]; then
        for pid in $pidlist; do
            address=$(grep -oPz '(?<=DBUS_SESSION_BUS_ADDRESS=).*' "/proc/$pid/environ" 2>/dev/null)
            if [[ -n $address ]]; then
                export DBUS_SESSION_BUS_ADDRESS=$address
                break
            fi
        done
    else
        echo "${0##*/}: unable to detect pids in use by '$USER'" >&2
        exit 1
    fi
fi

if [[ -n $DBUS_SESSION_BUS_ADDRESS ]]; then
    notify-send "$@"
else
    echo "${0##*/}: unable to detect DBUS_SESSION_BUS_ADDRESS for '$USER'" >&2
    exit 1
fi
